# Generated by Django 5.2.8 on 2025-11-10 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_emoji', models.CharField(default='🧠', max_length=8)),
                ('professional_profile', models.CharField(choices=[('EST', 'Estudante'), ('EMPJ', 'Empreendedor Júnior'), ('ANJ', 'Analista de Dados Jr.'), ('FIN', 'Assistente Financeiro'), ('OUT', 'Outro')], default='EST', max_length=5)),
                ('bio', models.CharField(blank=True, max_length=240)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
