# Generated by Django 5.2.8 on 2025-11-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='excel_experience',
            field=models.CharField(blank=True, help_text='Nível de experiência em Excel.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_character',
            field=models.CharField(blank=True, help_text='Personagem herói ou vilão de DC ou Marvel.', max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_emoji',
            field=models.CharField(default='😀', max_length=8),
        ),
    ]
