# Generated by Django 5.2.8 on 2025-11-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidestep',
            name='phase',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
