# Generated by Django 5.2.8 on 2025-11-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0002_guidestep_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveIntegerField(unique=True, verbose_name='Número da Fase')),
                ('is_released', models.BooleanField(default=False, verbose_name='Liberada para todos os usuários?')),
            ],
            options={
                'verbose_name': 'Liberação de Fase',
                'verbose_name_plural': 'Liberações de Fases',
                'ordering': ('phase_number',),
            },
        ),
    ]
