# Generated by Django 5.2.8 on 2025-11-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0004_phaserelease_duration_minutes_userphaseattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaserelease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phases_images/', verbose_name='Imagem da Fase'),
        ),
        migrations.AddField(
            model_name='phaserelease',
            name='story',
            field=models.TextField(blank=True, verbose_name='História da Fase'),
        ),
    ]
