# Generated by Django 5.2.8 on 2025-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0005_phaserelease_image_phaserelease_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveIntegerField(verbose_name='Número da Fase')),
                ('question_text', models.TextField(verbose_name='Pergunta')),
                ('answer_text', models.CharField(max_length=10, verbose_name='Resposta (Verdadeiro/Falso)')),
            ],
            options={
                'verbose_name': 'Questão do Quiz',
                'verbose_name_plural': 'Questões do Quiz',
                'ordering': ('phase_number',),
            },
        ),
    ]
